replicaCount: 1

image:
  repository: moabukar/ml-app
  tag: "3bcc279"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  host: "ml-app.localhost"
  path: "/"
  pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi