apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-web-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ml-web-service
  template:
    metadata:
      labels:
        app: ml-web-service
    spec:
      containers:
        - name: ml-web-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
