# name: Publish Helm Chart

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - charts/mlops/**

# permissions:
#   contents: write


# jobs:
#   publish-helm-chart:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Setup Helm
#       uses: azure/setup-helm@v3
#       with:
#         version: v3.12.0

#     - name: Package Helm Chart
#       run: |
#         cd charts/mlops
#         helm package .
#         helm repo index . --url https://moabukar.github.io/mlops-demo

#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: charts/mlops

name: Publish Helm Chart

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Helm
      run: |
        sudo apt-get update
        sudo apt-get install -y helm

    - name: Package Helm Chart
      run: helm package charts/mlops --destination ./charts/

    - name: Update index.yaml
      run: helm repo index ./charts --url https://moabukar.github.io/mlops-demo/charts

    - name: Commit and Push
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add charts/
        git commit -m "Publish Helm chart"
        git push
